# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
zstyle :compinstall filename '/Users/ryan/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

setopt prompt_subst

source ~/ryscomacs/extras/zsh/zsh-colors.sh

function SystemBlock
{
    echo "%K{023}%F{252}[%T %F{000}%n%F{252}]"
}

function VCBlock
{
    vcStart="%K{238}%F{015}"
    vcEnd=""
    
    git branch >/dev/null 2>/dev/null && echo "$vcStart ± $vcEnd" && return
    hg root >/dev/null 2>/dev/null && echo "$vcStart ☿ $vcEnd" && return
    echo "%K{237} "
}

function PathBlock
{
    echo "%K{237}%F{252} %~"
}

promptCap=":"

PROMPT='$(SystemBlock)$(VCBlock)$(PathBlock)$promptCap%f%k '

if [ "`uname`" = "Darwin" ]; then
    alias dir='ls -G'
else
    alias dir='ls --color=auto'
fi

#
compdef -d svn

#
EDITOR=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient


#
if [ -z $NO_HIGHLIGHT ]; then
    source ~/ryscomacs/extras/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [ -z $NO_AUTOSUGGESTIONS ]; then
    source ~/ryscomacs/extras/zsh/zsh-autosuggestions.zsh
fi

